print("Please answer the following: ")
print()
adjective = input('adjective: ')
animal = input('animal: ')
exclamation = input('exclamation: ')
verb = input('verb: ')
verb = input('verb: ')
print()
print(f"The other day, I was really in trouble. It all started when I saw a very {adjective} {animal} {verb} down the hallway")
print(f"{exclamation.capitalize()} I yelled. But all I could think to do was to {verb} over and over. Miraculously, that caused it to stop,")
print(f"but it tried to {verb} right in front of my family.")